"""add-point_2D-to_embeddings

Revision ID: 2d1590f7cbb2
Revises: e54eedf07233
Create Date: 2026-05-21 19:35:42.091786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2d1590f7cbb2'
down_revision: Union[str, Sequence[str], None] = 'e54eedf07233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_embeddings', sa.Column('point_2D', Vector(2), nullable=True))
    op.add_column('job_description_embeddings', sa.Column('point_2D', Vector(2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_description_embeddings', 'point_2D')
    op.drop_column('candidate_embeddings', 'point_2D')
    # ### end Alembic commands ###
